sudo: false
cache: packages
language: r

r_packages:
  - covr

env:
  matrix:
  - _R_CHECK_SYSTEM_CLOCK_=0
  global:
    secure: Czq9IoCwnpwEV16TZuhltKQ6dO27yRuLZYnN1G3PL9YRPa3BLfIEPSUsLaDM7jfTn6JBc8gJ9o0aehOWdL0wQKWJyLswHHx5XAYmGNC7YH4Cwb7sI96JQhj2TsFOoHqb5bnYBEgPcQhGxj8NCLuc8OgIHAJbraLfkgjm5CMF7Z5K3nusl7CHlrIswDdu4iyHqbI0MVLypIzrfWINooYNCl+yqXrS5NcNi4c3puCIBQpLY43d5pRgBzVl8GVum/VjZmwDLbgBJTvMoiircEnmP5uCNEVrBmWRdIHBRNv6xqVv4YHMdpIyI8uJEOdBO6YRyyxNy+Zxo9BocGs1b+Csdd7i78e6IvGUALG4wEhJYkx/xtWgtXucpq2kAVo3w7fvMH0vNndUzKEwVuLMMtsAmaxLvnvv8NUS3755a7/e7+3buzgriLMXd8G6Id/39GCRIzYSpt9ZYRAgMy1kYIAaxLJe9MTjyxrkYGs9tjeY50vZKbHVNlYfFAIPr931eOMS7Xc7pX3bVmkdci+51mOMGm5/qlJixlAiNl24P514BDXGpxi+0Pp5c7azHilITOmMsAgCq94zACnaS88FdnBlP1a3t0kkPkjfeONED2hNGfmxWJLDUQ6o42SyGN58KYrNGUt3hnqXhqHwTp+Nu9o8jHp0+zxSRwZH1zT5OG30L5c=

matrix:
  include:
  - r: devel
    before_install:
      - sudo add-apt-repository -y ppa:opencpu/jq
      - sudo apt-get update
      - sudo apt-get install libjq-dev
    after_success:
      - Rscript -e 'library(covr); codecov()'
  - r: release
    os: osx
    osx_image: xcode10.1
    before_install:
    - sudo tlmgr install inconsolata
    - sw_vers
  - r: release
    before_install:
      - sudo add-apt-repository -y ppa:opencpu/jq
      - sudo apt-get update
  # - r: oldrel
  #   before_install:
  #     - sudo add-apt-repository -y ppa:opencpu/jq
  #     - sudo apt-get update
  # - r: 3.5
  #   before_install:
  #     - sudo add-apt-repository -y ppa:opencpu/jq
  #     - sudo apt-get update

before_install:
  - echo "TRAVIS_OS_NAME = $TRAVIS_OS_NAME"

addons:
  apt:
    packages:
    - ghostscript
    - graphviz
    - libnode-dev
    - libjq-dev
  homebrew:
    packages:
    - ghostscript
    - graphviz
    - jq

# after_success:
#   - test $TRAVIS_PULL_REQUEST == "false" &&
#     test $TRAVIS_BRANCH == "master" &&
#     bash deploy.sh
